# Generated by Django 5.0.7 on 2024-08-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'ordering': ['status', '-data']},
        ),
    ]
